---
- hosts: node-1
  tasks:
   - name: Install Nginx
     yum: pkg=nginx state=installed update_cache=true
     notify:
      - Start Nginx

  handlers:
   - name: Start Nginx
     service: name=nginx state=started
